"""initial schema

Revision ID: bfe5f434b4fe
Revises: 
Create Date: 2026-09-11 13:42:40.743058
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'bfe5f434b4fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_freshness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.String(length=32), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('records_ingested', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_freshness')),
    sa.UniqueConstraint('provider', 'dataset', name='uq_data_freshness_provider_dataset')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_markets')),
    sa.UniqueConstraint('code', name=op.f('uq_markets_code'))
    )
    op.create_index(op.f('ix_markets_created_at'), 'markets', ['created_at'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('target', sa.Enum('DIRECTION', 'EXPECTED_RETURN', 'VOLATILITY', name='predictiontarget', native_enum=False, length=24), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('TRAINING', 'VALIDATING', 'CANDIDATE', 'PRODUCTION', 'ARCHIVED', 'FAILED', name='modelstatus', native_enum=False, length=16), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('artifact_path', sa.Text(), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('train_start', sa.Date(), nullable=True),
    sa.Column('train_end', sa.Date(), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('feature_baseline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('name', 'version', name='uq_model_versions_name_version')
    )
    op.create_index(op.f('ix_model_versions_created_at'), 'model_versions', ['created_at'], unique=False)
    op.create_index('ix_model_versions_status_target', 'model_versions', ['status', 'target'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='eventseverity', native_enum=False, length=12), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_events'))
    )
    op.create_index('ix_system_events_component_created_at', 'system_events', ['component', 'created_at'], unique=False)
    op.create_index('ix_system_events_severity_created_at', 'system_events', ['severity', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'READONLY', name='userrole', native_enum=False, length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_prefs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_api_keys_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    op.create_index(op.f('ix_api_keys_created_at'), 'api_keys', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_action_created_at', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_user_id_created_at', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_table('backtests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality', sa.Enum('LIVE', 'DELAYED', 'EOD', 'HISTORICAL', 'SYNTHETIC', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('sortino_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('average_trade_return', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True),
    sa.Column('benchmark_return', sa.Float(), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_backtests_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtests'))
    )
    op.create_index(op.f('ix_backtests_created_at'), 'backtests', ['created_at'], unique=False)
    op.create_index(op.f('ix_backtests_model_version_id'), 'backtests', ['model_version_id'], unique=False)
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('open_time', sa.String(length=8), nullable=False),
    sa.Column('close_time', sa.String(length=8), nullable=False),
    sa.Column('yahoo_suffix', sa.String(length=8), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], name=op.f('fk_exchanges_market_id_markets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchanges')),
    sa.UniqueConstraint('code', name=op.f('uq_exchanges_code'))
    )
    op.create_index(op.f('ix_exchanges_created_at'), 'exchanges', ['created_at'], unique=False)
    op.create_index(op.f('ix_exchanges_market_id'), 'exchanges', ['market_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('split', sa.String(length=32), nullable=False),
    sa.Column('metric_name', sa.String(length=48), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_model_metrics_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_metrics'))
    )
    op.create_index('ix_model_metrics_model_version_id_split', 'model_metrics', ['model_version_id', 'split'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='tradingmode', native_enum=False, length=8), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('starting_cash', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('day_realized_pnl', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('day_pnl_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash >= 0', name=op.f('ck_portfolios_cash_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_portfolios_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('user_id', 'name', name='uq_portfolios_user_id_name')
    )
    op.create_index(op.f('ix_portfolios_created_at'), 'portfolios', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cash', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('exposure_pct', sa.Float(), nullable=True),
    sa.Column('drawdown_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_portfolio_snapshots_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolio_snapshots')),
    sa.UniqueConstraint('portfolio_id', 'snapshot_date', name='uq_portfolio_snapshots_pf_date')
    )
    op.create_index(op.f('ix_portfolio_snapshots_portfolio_id'), 'portfolio_snapshots', ['portfolio_id'], unique=False)
    op.create_table('regime_states',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('regime', sa.Enum('BULL', 'BEAR', 'SIDEWAYS', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'UNKNOWN', name='marketregime', native_enum=False, length=24), nullable=False),
    sa.Column('volatility_regime', sa.Enum('BULL', 'BEAR', 'SIDEWAYS', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'UNKNOWN', name='marketregime', native_enum=False, length=24), nullable=False),
    sa.Column('trend_strength', sa.Float(), nullable=True),
    sa.Column('realized_volatility', sa.Float(), nullable=True),
    sa.Column('breadth', sa.Float(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('fk_regime_states_exchange_id_exchanges'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regime_states')),
    sa.UniqueConstraint('exchange_id', 'trade_date', name='uq_regime_states_exch_date')
    )
    op.create_index(op.f('ix_regime_states_exchange_id'), 'regime_states', ['exchange_id'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('asset_type', sa.Enum('EQUITY', 'ETF', 'INDEX', name='assettype', native_enum=False, length=16), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('provider_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('delisted_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('fk_securities_exchange_id_exchanges'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_securities')),
    sa.UniqueConstraint('exchange_id', 'symbol', name='uq_securities_exchange_id_symbol')
    )
    op.create_index('ix_securities_active_type', 'securities', ['is_active', 'asset_type'], unique=False)
    op.create_index(op.f('ix_securities_created_at'), 'securities', ['created_at'], unique=False)
    op.create_index(op.f('ix_securities_exchange_id'), 'securities', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_securities_isin'), 'securities', ['isin'], unique=False)
    op.create_index('ix_securities_sector', 'securities', ['sector'], unique=False)
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('backtest_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('costs', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=True),
    sa.Column('holding_days', sa.Integer(), nullable=True),
    sa.Column('exit_reason', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], name=op.f('fk_backtest_trades_backtest_id_backtests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_backtest_trades_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_trades'))
    )
    op.create_index(op.f('ix_backtest_trades_backtest_id'), 'backtest_trades', ['backtest_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_corporate_actions_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions')),
    sa.UniqueConstraint('security_id', 'ex_date', 'action_type', name='uq_corporate_actions_sec_exdate_type')
    )
    op.create_index(op.f('ix_corporate_actions_created_at'), 'corporate_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_security_id'), 'corporate_actions', ['security_id'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('profit_growth', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roce', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('earnings_growth', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_fundamentals_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamentals')),
    sa.UniqueConstraint('security_id', 'as_of_date', 'period', name='uq_fundamentals_sec_date_period')
    )
    op.create_index(op.f('ix_fundamentals_created_at'), 'fundamentals', ['created_at'], unique=False)
    op.create_index('ix_fundamentals_security_id_reported_at', 'fundamentals', ['security_id', 'reported_at'], unique=False)
    op.create_table('intraday_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('bar_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.Enum('LIVE', 'DELAYED', 'EOD', 'HISTORICAL', 'SYNTHETIC', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('high >= low', name=op.f('ck_intraday_data_intraday_high_ge_low')),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name=op.f('ck_intraday_data_intraday_positive')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_intraday_data_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intraday_data')),
    sa.UniqueConstraint('security_id', 'bar_timestamp', 'interval', name='uq_intraday_data_sec_ts_interval')
    )
    op.create_index('ix_intraday_data_security_id_bar_timestamp', 'intraday_data', ['security_id', 'bar_timestamp'], unique=False)
    op.create_table('news',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_news_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_news')),
    sa.UniqueConstraint('content_hash', name='uq_news_content_hash')
    )
    op.create_index('ix_news_published_at', 'news', ['published_at'], unique=False)
    op.create_index(op.f('ix_news_security_id'), 'news', ['security_id'], unique=False)
    op.create_index('ix_news_security_id_published_at', 'news', ['security_id', 'published_at'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('target', sa.Enum('DIRECTION', 'EXPECTED_RETURN', 'VOLATILITY', name='predictiontarget', native_enum=False, length=24), nullable=False),
    sa.Column('raw_probability', sa.Float(), nullable=True),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('predicted_volatility', sa.Float(), nullable=True),
    sa.Column('feature_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('data_quality', sa.Enum('LIVE', 'DELAYED', 'EOD', 'HISTORICAL', 'SYNTHETIC', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('horizon_days > 0', name=op.f('ck_predictions_horizon_positive')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_predictions_model_version_id_model_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_predictions_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_predictions')),
    sa.UniqueConstraint('security_id', 'model_version_id', 'as_of_date', 'horizon_days', name='uq_predictions_sec_model_date_horizon')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_model_version_id'), 'predictions', ['model_version_id'], unique=False)
    op.create_index('ix_predictions_security_id_as_of_date', 'predictions', ['security_id', 'as_of_date'], unique=False)
    op.create_table('price_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.Enum('LIVE', 'DELAYED', 'EOD', 'HISTORICAL', 'SYNTHETIC', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('high >= low', name=op.f('ck_price_data_high_ge_low')),
    sa.CheckConstraint('high >= open AND high >= close', name=op.f('ck_price_data_high_is_max')),
    sa.CheckConstraint('low <= open AND low <= close', name=op.f('ck_price_data_low_is_min')),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name=op.f('ck_price_data_prices_positive')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_price_data_volume_non_negative')),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_price_data_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_data')),
    sa.UniqueConstraint('security_id', 'trade_date', name='uq_price_data_sec_date')
    )
    op.create_index('ix_price_data_sec_date', 'price_data', ['security_id', 'trade_date'], unique=False)
    op.create_table('quotes',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('previous_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('change', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('day_open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('day_high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('day_low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('quality', sa.Enum('LIVE', 'DELAYED', 'EOD', 'HISTORICAL', 'SYNTHETIC', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('source_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_quotes_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('security_id', name=op.f('pk_quotes'))
    )
    op.create_table('technical_features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('feature_set_version', sa.String(length=32), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_technical_features_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technical_features')),
    sa.UniqueConstraint('security_id', 'trade_date', 'feature_set_version', name='uq_technical_features_sec_date_version')
    )
    op.create_index('ix_technical_features_security_id_trade_date', 'technical_features', ['security_id', 'trade_date'], unique=False)
    op.create_table('sentiment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('news_id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.Enum('POSITIVE', 'NEUTRAL', 'NEGATIVE', name='sentimentlabel', native_enum=False, length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('analyzer', sa.String(length=64), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_sentiment_sentiment_conf_range')),
    sa.CheckConstraint('score >= -1 AND score <= 1', name=op.f('ck_sentiment_sentiment_score_range')),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], name=op.f('fk_sentiment_news_id_news'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_sentiment_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentiment')),
    sa.UniqueConstraint('news_id', name=op.f('uq_sentiment_news_id'))
    )
    op.create_index(op.f('ix_sentiment_security_id'), 'sentiment', ['security_id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('signal', sa.Enum('STRONG_BUY', 'BUY', 'HOLD', 'SELL', 'STRONG_SELL', 'NO_ACTION', name='signaltype', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'SUPERSEDED', 'INVALIDATED', name='signalstatus', native_enum=False, length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MODERATE', 'HIGH', 'VERY_HIGH', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('entry_low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('entry_high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('reward_to_risk', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('regime', sa.Enum('BULL', 'BEAR', 'SIDEWAYS', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'UNKNOWN', name='marketregime', native_enum=False, length=24), nullable=True),
    sa.Column('rationale', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_quality', sa.Enum('LIVE', 'DELAYED', 'EOD', 'HISTORICAL', 'SYNTHETIC', name='dataquality', native_enum=False, length=16), nullable=False),
    sa.Column('price_as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invalidation_reason', sa.String(length=256), nullable=True),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_signals_signal_confidence_range')),
    sa.CheckConstraint('expires_at > generated_at', name=op.f('ck_signals_signal_expiry_after_generation')),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], name=op.f('fk_signals_model_version_id_model_versions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], name=op.f('fk_signals_prediction_id_predictions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_signals_security_id_securities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_signals'))
    )
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_opportunity_score'), 'signals', ['opportunity_score'], unique=False)
    op.create_index('ix_signals_security_id_generated_at', 'signals', ['security_id', 'generated_at'], unique=False)
    op.create_index(op.f('ix_signals_signal'), 'signals', ['signal'], unique=False)
    op.create_index('ix_signals_status_generated_at', 'signals', ['status', 'generated_at'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('signal_id', sa.BigInteger(), nullable=True),
    sa.Column('alert_type', sa.Enum('SIGNAL', 'STOP_LOSS_HIT', 'TAKE_PROFIT_HIT', 'PRICE_MOVE', 'VOLUME_SPIKE', 'NEWS', 'PREDICTION_CHANGE', 'SYSTEM', 'RISK_BREACH', name='alerttype', native_enum=False, length=24), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alertseverity', native_enum=False, length=12), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', 'SUPPRESSED', name='alertstatus', native_enum=False, length=12), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('channels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_alerts_security_id_securities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_alerts_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_alerts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index('ix_alerts_dedupe_key_created_at', 'alerts', ['dedupe_key', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_security_id'), 'alerts', ['security_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index('ix_alerts_user_id_created_at', 'alerts', ['user_id', 'created_at'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus', native_enum=False, length=8), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('opening_signal_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity >= 0', name=op.f('ck_holdings_holding_qty_non_negative')),
    sa.ForeignKeyConstraint(['opening_signal_id'], ['signals.id'], name=op.f('fk_holdings_opening_signal_id_signals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_holdings_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_holdings_security_id_securities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings'))
    )
    op.create_index(op.f('ix_holdings_created_at'), 'holdings', ['created_at'], unique=False)
    op.create_index('ix_holdings_portfolio_id_status', 'holdings', ['portfolio_id', 'status'], unique=False)
    op.create_index(op.f('ix_holdings_security_id'), 'holdings', ['security_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside', native_enum=False, length=8), nullable=False),
    sa.Column('order_type', sa.Enum('MARKET', 'LIMIT', 'STOP', name='ordertype', native_enum=False, length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUBMITTED', 'FILLED', 'PARTIALLY_FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus', native_enum=False, length=20), nullable=False),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='tradingmode', native_enum=False, length=8), nullable=False),
    sa.Column('broker', sa.String(length=32), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('rejection_reason', sa.String(length=256), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_orders_order_qty_positive')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_orders_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_orders_security_id_securities'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name=op.f('fk_orders_signal_id_signals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('idempotency_key', name='uq_orders_idempotency_key')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_portfolio_id_status', 'orders', ['portfolio_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_security_id'), 'orders', ['security_id'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside', native_enum=False, length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('reference_price', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('slippage_cost', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('exit_reason', sa.Enum('STOP_LOSS', 'TAKE_PROFIT', 'SIGNAL_EXIT', 'TIME_EXIT', 'MANUAL', 'RISK_EXIT', name='exitreason', native_enum=False, length=20), nullable=True),
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='tradingmode', native_enum=False, length=8), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('quantity > 0 AND price > 0', name=op.f('ck_paper_trades_trade_positive')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_paper_trades_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_paper_trades_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], name=op.f('fk_paper_trades_security_id_securities'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trades'))
    )
    op.create_index(op.f('ix_paper_trades_order_id'), 'paper_trades', ['order_id'], unique=False)
    op.create_index('ix_paper_trades_portfolio_id_executed_at', 'paper_trades', ['portfolio_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_paper_trades_security_id'), 'paper_trades', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trades_security_id'), table_name='paper_trades')
    op.drop_index('ix_paper_trades_portfolio_id_executed_at', table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_order_id'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_orders_security_id'), table_name='orders')
    op.drop_index('ix_orders_portfolio_id_status', table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_holdings_security_id'), table_name='holdings')
    op.drop_index('ix_holdings_portfolio_id_status', table_name='holdings')
    op.drop_index(op.f('ix_holdings_created_at'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index('ix_alerts_user_id_created_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_security_id'), table_name='alerts')
    op.drop_index('ix_alerts_dedupe_key_created_at', table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ix_signals_status_generated_at', table_name='signals')
    op.drop_index(op.f('ix_signals_signal'), table_name='signals')
    op.drop_index('ix_signals_security_id_generated_at', table_name='signals')
    op.drop_index(op.f('ix_signals_opportunity_score'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_sentiment_security_id'), table_name='sentiment')
    op.drop_table('sentiment')
    op.drop_index('ix_technical_features_security_id_trade_date', table_name='technical_features')
    op.drop_table('technical_features')
    op.drop_table('quotes')
    op.drop_index('ix_price_data_sec_date', table_name='price_data')
    op.drop_table('price_data')
    op.drop_index('ix_predictions_security_id_as_of_date', table_name='predictions')
    op.drop_index(op.f('ix_predictions_model_version_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_news_security_id_published_at', table_name='news')
    op.drop_index(op.f('ix_news_security_id'), table_name='news')
    op.drop_index('ix_news_published_at', table_name='news')
    op.drop_table('news')
    op.drop_index('ix_intraday_data_security_id_bar_timestamp', table_name='intraday_data')
    op.drop_table('intraday_data')
    op.drop_index('ix_fundamentals_security_id_reported_at', table_name='fundamentals')
    op.drop_index(op.f('ix_fundamentals_created_at'), table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index(op.f('ix_corporate_actions_security_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_created_at'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_backtest_trades_backtest_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_index('ix_securities_sector', table_name='securities')
    op.drop_index(op.f('ix_securities_isin'), table_name='securities')
    op.drop_index(op.f('ix_securities_exchange_id'), table_name='securities')
    op.drop_index(op.f('ix_securities_created_at'), table_name='securities')
    op.drop_index('ix_securities_active_type', table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_regime_states_exchange_id'), table_name='regime_states')
    op.drop_table('regime_states')
    op.drop_index(op.f('ix_portfolio_snapshots_portfolio_id'), table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_created_at'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index('ix_model_metrics_model_version_id_split', table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_exchanges_market_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_created_at'), table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index(op.f('ix_backtests_model_version_id'), table_name='backtests')
    op.drop_index(op.f('ix_backtests_created_at'), table_name='backtests')
    op.drop_table('backtests')
    op.drop_index('ix_audit_logs_user_id_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_created_at'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_system_events_severity_created_at', table_name='system_events')
    op.drop_index('ix_system_events_component_created_at', table_name='system_events')
    op.drop_table('system_events')
    op.drop_index('ix_model_versions_status_target', table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_created_at'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_markets_created_at'), table_name='markets')
    op.drop_table('markets')
    op.drop_table('data_freshness')
    # ### end Alembic commands ###
